---
- name: Archive task
  hosts: all
  become: true
  tasks:
  - name: Create archive
    archive:
     path: /usr/src/data/
     dest: /opt/data/official.tar.gz
     format: gz
  - name: change ownership file
    file:
     path: /opt/data/official.tar.gz
     owner: "{{ ansible_user }}"
     group: "{{ ansible_user }}"
